### PR TITLE
simplify Dockerfile

### PR DESCRIPTION
**Pull request by JakeUrban**
Makes some minor changes to the Dockerfile to make it a bit simpler:

- Uses `WORKDIR` to create the `/code` directory, allowing the `COPY` command to use `. .`
- Removed unnecessary installs (these can always be installed when `docker exec`'ed in the container)
- Removes `ENV` commands.
    - I'm not sure if this would break anything, but we should be able to specify these environment variables at runtime instead of having defaults built into the image
- Removes the `EXPOSE` command, since it actually has no affect

### CODE REVIEW

**Comment by reecexlm** [comment]
we need to have SEPs pass before this can be merged. partners are testing with these dockers.

**Comment by JakeUrban** [comment]
Yes, I think there needs to be a pipeline PR, since it looks like our CI processes relied on the default values being set.

The other option is to keep the defaults. Its not a big deal to keep them, but my thought was that we shouldn't set defaults in the image everyone uses just for our own pipelines.

**Comment by JakeUrban** [comment]
Actually, it looks like this may require a kube PR, since the pipelines repo simply deploys the k8 spec files: https://github.com/stellar/pipelines/blob/master/anchor-platform/Jenkinsfile-preview

**Review by marcelosalloum — APPROVED** [review]
LGTM!

Just make sure to update the deploys for `dev` and `prd` in stellar/kube.

**Pull request merged**
