### PR TITLE
Add SEP-9 field types country_code, language_code, and phone_number to SEP-12 fields

### PR DESCRIPTION
**Pull request by erika-sdf**
<details>
  <summary>PR Checklist</summary>

### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `paymentservice.stellar`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
</details>

### What

Add SEP-9 field types country_code, language_code, and phone_number to SEP-12 fields.

### Why
SEP-12 does not currently support these field types.

### CODE REVIEW

**Review by lijamie98 — APPROVED** [review]
LGTM

**Review by marcelosalloum — APPROVED** [review]
LGTM!

**Comment by erika-sdf** [comment]
Sorry, I didnt mean for this to be reviewed yet. I think Jake suggested we should not introduce these fields as types, and instead update the docs to keep them as strings. I'll close out this PR

**Comment by erika-sdf** [comment]
https://github.com/stellar/stellar-protocol/pull/1296

**Pull request closed without merging**
