### PR TITLE
platform: remove all SEP-24 related code

### PR DESCRIPTION
**Pull request by JakeUrban**
<details>
  <summary>PR Checklist</summary>

### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `paymentservice.stellar`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
</details>

### What

Removes all SEP-24 related code from the Platform.

### Why

The platform will not support SEP-24 for the foreseeable future and the project no longer needs the code to be used as a reference for implementing other SEPs.

### CODE REVIEW

**Review by reecexlm — APPROVED** [review]
LGTM

**Comment by reecexlm** [comment]
one question i have, is if this is working code, can we leave it as a disabled?

**Comment by lijamie98** [comment]
@reecexlm It is possible to leave them as disabled or deleted. 
@JakeUrban I had not have time to create example projects yet. Can we wait a little longer?

**Comment by reecexlm** [comment]
i agree that we should not have unfinished code in our "main" branch. if this is working, complete code (code complete)  then i don't see a reason to remove it. its a feature that is ready and can be toggled on/off right? unless i am missing some context about why we would not want a feature available in our code base that might be used long term.  if its still WIP then IMHO, it should live in a branch until it is ready to be part of our main branch.  i might also be missing some context on our branch strategy.  thanks!

**Pull request merged**
