### PR TITLE
Merge release 2.0.0 rc1 to `main`

### PR DESCRIPTION
**Pull request by lijamie98**
<details>
  <summary>PR Checklist</summary>

### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `paymentservice.stellar`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
</details>

### What

Merge release 2.0.0 rc1 to main

### Why

Release preparation

### CODE REVIEW

**Comment by JakeUrban** [comment]
Are you sure you want to merge this to main and not develop?

**Review by Ifropc — APPROVED** [review]

**Comment by lijamie98** [comment]
> Are you sure you want to merge this to main and not develop?

This is done according to the release process: https://github.com/stellar/java-stellar-anchor-sdk/issues/809

**Comment by lijamie98** [comment]
Merge release `2.0.0-rc1`

**Comment by lijamie98** [comment]
Merge release `2.0.0-rc1`

**Pull request merged**
