### PR TITLE
[Chore] Merge `develop` into `feature/v3`

### PR DESCRIPTION
**Pull request by philipliu**
### Description

This merges `develop` into `feature/v3`.

### Context

This catches up `feature/v3` so it can be merged into `develop` later.

### Testing

- `./gradlew test`

### Documentation

N/A

### Known limitations

N/A

### CODE REVIEW

**Comment by JiahuiWho** [comment]
Is it suppose to include these much commit? I made a merge 2 weeks ago https://github.com/stellar/java-stellar-anchor-sdk/pull/1553

**Comment by philipliu** [comment]
@JiahuiWho Looks like it was squash merged by accident https://github.com/stellar/java-stellar-anchor-sdk/commit/0b327e91aaaf99c787212810db3b726a70859ba4

**Comment by JiahuiWho** [comment]
LGTM

Curious how to tell if it's a regular commit or a squash commit

**Review by JiahuiWho — APPROVED** [review]

**Comment by philipliu** [comment]
@JiahuiWho The commit has a large diff. A merge commit would be empty.

**Pull request merged**
