### PR TITLE
Back merge `2.2.1` to `develop` - Fix the mistakenly removed printVersionName Gradle task

### PR DESCRIPTION
**Pull request by lijamie98**
### Description
Back merge `2.2.1` to `develop` 
Fix the mistakenly removed printVersionName Gradle task

### Context
Back merge hotfix `2.2.1`

### Testing

`./gradlew test`

### Known limitations
NA

### CODE REVIEW

**Review by philipliu — APPROVED** [review]
LGTM

**Review by JakeUrban — APPROVED** [review]
LGTM

Separately, what do you think about adding a `--version` argument to the jar, rather than a gradle task?

**Comment by lijamie98** [comment]
This PR was incorrectly created with the `main` branch. Closing this and creating a new one.

**Comment by lijamie98** [comment]
> LGTM
> 
> Separately, what do you think about adding a `--version` argument to the jar, rather than a gradle task?

Do you mean adding `--version` to [`ServiceRunner.java`?](https://github.com/stellar/java-stellar-anchor-sdk/blob/develop/service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java#L16)

**Comment by JakeUrban** [comment]
Yes

**Pull request closed without merging**
