### PR TITLE
callbackApi: design endpoint to be called for a unique `stellar_address:memo` pair

### PR DESCRIPTION
**Pull request by marcelosalloum**
<details>
  <summary>PR Checklist</summary>

### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `paymentservice.stellar`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
</details>

### What

Design a callback API endpoint so the Platform can call the Anchor backend for a unique `stellar_address:memo` pair, where the stellar_addres must be the address of an existing account in the Stellar network.

#### Request & Response formats

*Request:*
```
GET {callbackAPI}/unique_address
```

*Response:*
```json
{
  "unique_address": {
    "stellar_address": "string",
    "memo": "string"
  }
}
```

#### Sequence Diagram

Here's an example of how this flow would work, considering a scenario where the Receiving Anchor would create the unique `stellar_account:memo` pairs in Circle:

```mermaid
sequenceDiagram
    title: SEP-31 Transaction Flow with "{callbackAPI}/unique_address"
    participant Stellar
    participant Sending Anchor
    participant (Receiving) Platform
    participant (Receiving) Anchor
    participant Circle
    Sending Anchor->>+(Receiving) Platform: POST {sep31}/transactions
    opt Call {callbackAPI}/unique_address based on the platform configuration
        (Receiving) Platform->>+(Receiving) Anchor: GET {callbackAPI}/unique_address
        (Receiving) Anchor->>+Circle: Generate a blockchain address.
        Circle-->>-(Receiving) Anchor: Returns new unique "stellar_address:memo" pair.
        (Receiving) Anchor-->>-(Receiving) Platform: Returns new unique "stellar_address:memo" pair.
    end
    (Receiving) Platform-->>(Receiving) Platform: Finishes building the SEP-31 transaction with the unique "stellar_address:memo" pair.
    (Receiving) Platform-->>-Sending Anchor: Returns the SEP-31 transaction.
    Sending Anchor->>Stellar: Make Stellar payment.
    Stellar-->>+(Receiving) Platform: Platform detects a Stellar payment happened using the unique "stellar_address:memo" pair.
    (Receiving) Platform->>(Receiving) Anchor: Platform sends a TransactionEvent with the Transaction Info.
    (Receiving) Anchor->>(Receiving) Anchor: Proceeds with the rest of the flow, sending the payment to the Receiving Client.
    (Receiving) Anchor->>+(Receiving) Platform: PATCH {platformAPI}/transaction with the updated SEP-31 transaction status.
    (Receiving) Platform-->>(Receiving) Platform: Update the transaction status.
    Sending Anchor->>+(Receiving) Platform: GET {sep31}/transactions/:id to check the status of the transaction.
    (Receiving) Platform-->>-Sending Anchor: Return the transaction information.
```

### Why

To partially address #377.

### CODE REVIEW

**Comment by reecexlm** [comment]
is there a sequence diagram you could add with this change so its easy to understand the transaction flow?

**Comment by spolaore** [comment]
Looking good @marcelosalloum!
Just one question: any specific scenario in mind for adding an idempotency_key here?

**Comment by marcelosalloum** [comment]
> Looking good @marcelosalloum! Just one question: any specific scenario in mind for adding an idempotency_key here?

Good point! I don't really see a reason for that right now, it was just inspiration from the Circle API.
Maybe it's not worth adding it here, so we can keep things simpler. WDYT?

**Comment by spolaore** [comment]
I think in some cases it's worth the hassle, but for this particular operation, we could do as you suggested and keep it simpler!

**Review by erika-sdf — APPROVED** [review]

**Pull request merged**
