### PR TITLE
hotfix: solve issue where `uniqueAddressService` was crashing

### LINKED ISSUE #443: SepException: distributionWallet is empty
Reference Server is failing with following exception. This issue addresses the bug and adds test coverage to ensure its caught in unit tests.

15:29:19.689 WARN  - o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'uniqueAddressService' defined in URL [jar:file:/app/anchor-platform-runner.jar!/BOOT-INF/lib/anchor-reference-server-0.1.1-plain.jar!/org/stellar/anchor/reference/service/UniqueAddressService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.stellar.anchor.reference.service.UniqueAddressService]: Constructor threw exception; nested exception is org.stellar.anchor.api.exception.SepException: distributionWallet is empty
15:29:19.689 INFO  - o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
15:29:19.888 INFO  - o.s.b.a.l.ConditionEvaluationReportLoggingListener -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
15:29:20.090 ERROR - o.s.b.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'uniqueAddressService' defined in URL [jar:file:/app/anchor-platform-runner.jar!/BOOT-INF/lib/anchor-reference-server-0.1.1-plain.jar!/org/stellar/anchor/reference/service/UniqueAddressService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.stellar.anchor.reference.service.UniqueAddressService]: Constructor threw exception; nested exception is org.stellar.anchor.api.exception.SepException: distributionWallet is empty
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) [spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) [spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) [spring-boot-2.6.3.jar!/:2.6.3]
	at org.stellar.anchor.reference.AnchorReferenceServer.start(AnchorReferenceServer.java:35) [anchor-reference-server-0.1.1-plain.jar!/:?]
	at org.stellar.anchor.platform.ServiceRunner.startAnchorReferenceServer(ServiceRunner.java:64) [classes!/:?]
	at org.stellar.anchor.platform.ServiceRunner.main(ServiceRunner.java:29) [classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [anchor-platform-runner.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [anchor-platform-runner.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [anchor-platform-runner.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [anchor-platform-runner.jar:?]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.stellar.anchor.reference.service.UniqueAddressService]: Constructor threw exception; nested exception is org.stellar.anchor.api.exception.SepException: distributionWallet is empty
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.15.jar!/:5.3.15]
	... 27 more
Caused by: org.stellar.anchor.api.exception.SepException: distributionWallet is empty
	at org.stellar.anchor.reference.service.UniqueAddressService.<init>(UniqueAddressService.java:20) ~[anchor-reference-server-0.1.1-plain.jar!/:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.15.jar!/:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.15.jar!/:5.3.15]
	... 27 more
Reeces-MacBook-Pro~/dev/java-stellar-anchor-sdk %

### PR DESCRIPTION
**Pull request by marcelosalloum**
<details>
  <summary>PR Checklist</summary>

### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `paymentservice.stellar`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
</details>

### What

Create annotation `ConditionalOnPropertyNotEmpty` and add it to the `UniqueAddressController` and `UniqueAddressService`, so they are only instantiated when the `anchor.settings.distributionWallet` property is not empty.

### Why

Close #443

### CODE REVIEW

**Comment by reecexlm** [comment]
do we still need to create a github issue to add unit test coverage with this hotfix?

**Review by reecexlm — APPROVED** [review]

**Comment by reecexlm** [comment]
LGTM, made one comment above about creating a tech debt item if appropriate but should not block this merging.

**Comment by lijamie98** [comment]
Love it!

**Review by lijamie98 — COMMENTED** [review]
LGTM!

**Pull request merged**
